<script setup lang="ts">
import { RefreshCw, Save, Trash2 } from "lucide-vue-next";
import type { PeriodRange, ScorecardComputation } from "~/types/api";
import { currentOperationalPeriod, MONTHS, periodToQuery } from "~/utils/period";
import { formatNumber, formatPercent } from "~/utils/format";

defineProps<{ canClear: boolean }>();
const api=useApi();const period=ref<PeriodRange>(currentOperationalPeriod());const rows=ref<ScorecardComputation[]>([]);const history=ref<ScorecardComputation[]>([]);const loading=ref(true),busy=ref(false);const message=ref(""),tone=ref<"success"|"error">("success");const selected=ref("");
function competencies(p:PeriodRange){const out:Array<{year:number;month:number}>=[];let y=p.startYear,m=p.startMonth;while(y<p.endYear||(y===p.endYear&&m<=p.endMonth)){out.push({year:y,month:m});m++;if(m===13){m=1;y++;}}return out;}
function notify(text:string,kind:"success"|"error"="success"){message.value=text;tone.value=kind;}
async function load(){loading.value=true;try{const months=competencies(period.value);rows.value=await Promise.all(months.map(({year,month})=>api.get<ScorecardComputation>("/scorecard",{year,month})));history.value=(await api.get<{snapshots:ScorecardComputation[]}>("/scorecard/history",periodToQuery(period.value))).snapshots;selected.value=selected.value||`${months.at(-1)?.year}-${months.at(-1)?.month}`;}catch(cause){notify(cause instanceof Error?cause.message:"Erro ao carregar scorecard.","error");}finally{loading.value=false;}}
const current=computed(()=>{const [year,month]=selected.value.split("-").map(Number);return rows.value.find(row=>row.year===year&&row.month===month)??null;});
const totals=computed(()=>({points:rows.value.reduce((sum,row)=>sum+row.result.totalPontos,0),possible:rows.value.reduce((sum,row)=>sum+row.result.pontosPossiveisMes,0)}));
async function saveSnapshot(){if(!current.value)return;busy.value=true;try{await api.post("/scorecard",{year:current.value.year,month:current.value.month,overrides:{}});notify("Snapshot salvo com os valores publicados atuais.");await load();}catch(cause){notify(cause instanceof Error?cause.message:"Erro ao salvar snapshot.","error");}finally{busy.value=false;}}
async function savePanelPeriod(){busy.value=true;try{await api.patch("/scorecard/panel-period",period.value);notify("Período do Painel Geral atualizado.");}catch(cause){notify(cause instanceof Error?cause.message:"Erro ao salvar período.","error");}finally{busy.value=false;}}
async function clearHistory(){if(!confirm("Excluir os snapshots salvos deste ciclo?"))return;busy.value=true;try{await api.delete("/scorecard/history",undefined,periodToQuery(period.value));notify("Histórico do ciclo excluído.");await load();}catch(cause){notify(cause instanceof Error?cause.message:"Erro ao excluir histórico.","error");}finally{busy.value=false;}}
watch(period,load,{deep:true});onMounted(load);
</script>
<template><div class="stack"><section class="surface"><header class="surface-header"><div><h2>Scorecard consolidado — Administração</h2><p>Valores ao vivo das publicações; snapshots são somente uma trilha histórica.</p></div><div class="toolbar"><PeriodSelector v-model="period"/><button class="btn btn-icon" @click="load"><RefreshCw :size="16"/></button></div></header><div class="surface-body stack"><div v-if="message" class="notice" :class="tone">{{message}}</div><div class="toolbar"><label class="field"><span>Competência</span><select v-model="selected"><option v-for="row in rows" :key="`${row.year}-${row.month}`" :value="`${row.year}-${row.month}`">{{MONTHS[row.month-1]}}/{{row.year}}</option></select></label><button class="btn primary" :disabled="busy||!current" @click="saveSnapshot"><Save :size="15"/> Salvar snapshot</button><button class="btn" :disabled="busy" @click="savePanelPeriod">Usar ciclo no Painel Geral</button><button v-if="canClear" class="btn danger" :disabled="busy" @click="clearHistory"><Trash2 :size="15"/> Limpar histórico</button></div><div v-if="loading" class="loading-state"><div class="spinner"/></div><template v-else><div class="metric-grid"><MetricCard label="Pontos no ciclo" :value="formatNumber(totals.points,1)" :detail="`de ${formatNumber(totals.possible,1)} possíveis nos dados disponíveis`"/><MetricCard label="Atendimento do ciclo" :value="formatPercent(totals.possible?totals.points/totals.possible*100:0)"/><MetricCard label="Snapshots salvos" :value="formatNumber(history.length)"/><MetricCard label="Competências" :value="formatNumber(rows.length)"/></div><div v-if="current" class="table-wrap"><table class="data-table"><thead><tr><th>Indicador</th><th class="numeric">Peso</th><th class="numeric">Meta</th><th class="numeric">Valor publicado</th><th>Status</th><th class="numeric">Pontos</th><th class="numeric">Possíveis</th></tr></thead><tbody><tr v-for="row in current.result.rows" :key="row.key"><td><strong>{{row.label}}</strong></td><td class="numeric">{{formatPercent(row.peso)}}</td><td class="numeric">{{formatNumber(row.meta,2)}}{{row.unit}}</td><td class="numeric">{{row.value===null?'—':`${formatNumber(row.value,2)}${row.unit}`}}</td><td><span class="badge" :class="row.hasValue?(row.pass?'good':'bad'):''">{{!row.hasValue?'Sem dados':row.pass?'Atingiu':'Não atingiu'}}</span></td><td class="numeric">{{formatNumber(row.pontos,2)}}</td><td class="numeric">{{formatNumber(row.pontosPossiveis,2)}}</td></tr></tbody><tfoot><tr><td colspan="5"><strong>Total mensal</strong></td><td class="numeric"><strong>{{formatNumber(current.result.totalPontos,2)}}</strong></td><td class="numeric"><strong>{{formatNumber(current.result.pontosPossiveisMes,2)}}</strong></td></tr></tfoot></table></div></template></div></section></div></template>
