"""baseline schema

Cria as 20 tabelas equivalentes ao `prisma/schema.prisma` do Next.js original,
incluindo as extensões aplicadas fora do Prisma Migrate em
`prisma/manual/005_idp_rso_versions.sql` (IdpRsoRecord), `006_indicator_justifications.sql`
(IndicatorJustification) e `007_indicator_publication_cycle.sql` +
`008_fix_publication_cycle_year_convention.sql` (colunas de ciclo, índice
único parcial `IndicatorPublication_active_cycle_key` e o CHECK
`IndicatorPublication_cycle_consistency_check` já na convenção corrigida).
Roda em um banco vazio. Ver docs/backend-migration-decisions.md.

Revision ID: 0c528c3c79e5
Revises:
Create Date: 2026-08-19 09:06:10.768518
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0c528c3c79e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccidentMonthlyRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('caf', sa.Integer(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('AccidentMonthlyRecord_year_month_idx', 'AccidentMonthlyRecord', ['year', 'month'], unique=False)
    op.create_index('AccidentMonthlyRecord_year_month_key', 'AccidentMonthlyRecord', ['year', 'month'], unique=True)
    op.create_table('AccidentUnitRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unitKey', sa.String(), nullable=False),
    sa.Column('saf', sa.Integer(), nullable=False),
    sa.Column('caf', sa.Integer(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('AccidentUnitRecord_unit_idx', 'AccidentUnitRecord', ['unit'], unique=False)
    op.create_index('AccidentUnitRecord_year_month_idx', 'AccidentUnitRecord', ['year', 'month'], unique=False)
    op.create_index('AccidentUnitRecord_year_month_unitKey_key', 'AccidentUnitRecord', ['year', 'month', 'unitKey'], unique=True)
    op.create_table('AppSetting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('FiveSRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('businessKey', sa.String(), nullable=False),
    sa.Column('contentHash', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('aderencia', sa.Float(), nullable=False),
    sa.Column('areasCount', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('firstImportId', sa.String(), nullable=False),
    sa.Column('lastImportId', sa.String(), nullable=False),
    sa.Column('firstSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('FiveSRecord_businessKey_key', 'FiveSRecord', ['businessKey'], unique=True)
    op.create_index('FiveSRecord_unit_idx', 'FiveSRecord', ['unit'], unique=False)
    op.create_index('FiveSRecord_year_month_idx', 'FiveSRecord', ['year', 'month'], unique=False)
    op.create_table('IdpRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('businessKey', sa.String(), nullable=False),
    sa.Column('contentHash', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(), nullable=False),
    sa.Column('custoLinhaBase', sa.Float(), nullable=False),
    sa.Column('custoReal', sa.Float(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('firstImportId', sa.String(), nullable=False),
    sa.Column('lastImportId', sa.String(), nullable=False),
    sa.Column('firstSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IdpRecord_businessKey_key', 'IdpRecord', ['businessKey'], unique=True)
    op.create_index('IdpRecord_unit_idx', 'IdpRecord', ['unit'], unique=False)
    op.create_index('IdpRecord_year_month_idx', 'IdpRecord', ['year', 'month'], unique=False)
    op.create_table('IdpRsoRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('businessKey', sa.String(), nullable=False),
    sa.Column('contentHash', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('detectedUnit', sa.String(), nullable=True),
    sa.Column('unitAdjusted', sa.Boolean(), nullable=False),
    sa.Column('rsoNumero', sa.Integer(), nullable=False),
    sa.Column('detectedRsoNumero', sa.Integer(), nullable=True),
    sa.Column('rsoAdjusted', sa.Boolean(), nullable=False),
    sa.Column('referenceYear', sa.Integer(), nullable=False),
    sa.Column('referenceMonth', sa.Integer(), nullable=False),
    sa.Column('detectedReferenceYear', sa.Integer(), nullable=True),
    sa.Column('detectedReferenceMonth', sa.Integer(), nullable=True),
    sa.Column('referenceSource', sa.String(), nullable=False),
    sa.Column('referenceOriginalText', sa.String(), nullable=True),
    sa.Column('referenceAdjusted', sa.Boolean(), nullable=False),
    sa.Column('periodStart', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('periodEnd', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('emissionDate', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discData', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execucaoFases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('firstImportId', sa.String(), nullable=False),
    sa.Column('lastImportId', sa.String(), nullable=False),
    sa.Column('firstSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IdpRsoRecord_businessKey_key', 'IdpRsoRecord', ['businessKey'], unique=True)
    op.create_index('IdpRsoRecord_referenceYear_referenceMonth_idx', 'IdpRsoRecord', ['referenceYear', 'referenceMonth'], unique=False)
    op.create_index('IdpRsoRecord_unit_rsoNumero_idx', 'IdpRsoRecord', ['unit', 'rsoNumero'], unique=False)
    op.create_table('IndicatorResult',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('adherence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IndicatorResult_module_indicator_unit_year_month_key', 'IndicatorResult', ['module', 'indicator', 'unit', 'year', 'month'], unique=True)
    op.create_index('IndicatorResult_module_year_month_idx', 'IndicatorResult', ['module', 'year', 'month'], unique=False)
    op.create_table('RdoRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('businessKey', sa.String(), nullable=False),
    sa.Column('contentHash', sa.String(), nullable=False),
    sa.Column('dataReferencia', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('empresaNome', sa.String(), nullable=False),
    sa.Column('statusDescricao', sa.String(), nullable=False),
    sa.Column('relatorioId', sa.String(), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('disciplina', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('editedManually', sa.Boolean(), nullable=False),
    sa.Column('editedBy', sa.String(), nullable=True),
    sa.Column('editedAt', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('firstImportId', sa.String(), nullable=False),
    sa.Column('lastImportId', sa.String(), nullable=False),
    sa.Column('firstSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('RdoRecord_businessKey_key', 'RdoRecord', ['businessKey'], unique=True)
    op.create_index('RdoRecord_empresaNome_idx', 'RdoRecord', ['empresaNome'], unique=False)
    op.create_index('RdoRecord_statusDescricao_idx', 'RdoRecord', ['statusDescricao'], unique=False)
    op.create_index('RdoRecord_year_month_idx', 'RdoRecord', ['year', 'month'], unique=False)
    op.create_table('RncRecord',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('businessKey', sa.String(), nullable=False),
    sa.Column('contentHash', sa.String(), nullable=False),
    sa.Column('statusRnc', sa.String(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=False),
    sa.Column('dataCriacao', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('dataSolucao', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('tempoTratativa', sa.Float(), nullable=True),
    sa.Column('ofensor', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('editedManually', sa.Boolean(), nullable=False),
    sa.Column('editedBy', sa.String(), nullable=True),
    sa.Column('editedAt', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('firstImportId', sa.String(), nullable=False),
    sa.Column('lastImportId', sa.String(), nullable=False),
    sa.Column('firstSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('RncRecord_businessKey_key', 'RncRecord', ['businessKey'], unique=True)
    op.create_index('RncRecord_unidade_idx', 'RncRecord', ['unidade'], unique=False)
    op.create_index('RncRecord_year_month_idx', 'RncRecord', ['year', 'month'], unique=False)
    op.create_table('ScorecardSnapshot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('businessKey', sa.String(), nullable=False),
    sa.Column('contentHash', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('firstImportId', sa.String(), nullable=False),
    sa.Column('lastImportId', sa.String(), nullable=False),
    sa.Column('firstSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ScorecardSnapshot_businessKey_key', 'ScorecardSnapshot', ['businessKey'], unique=True)
    op.create_index('ScorecardSnapshot_year_month_idx', 'ScorecardSnapshot', ['year', 'month'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('emailVerified', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('role', postgresql.ENUM('VIEWER', 'ANALYST', 'ADMIN', name='Role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('authProvider', sa.String(), nullable=False),
    sa.Column('externalUserId', sa.String(), nullable=True),
    sa.Column('lastLoginAt', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('User_email_idx', 'User', ['email'], unique=False)
    op.create_index('User_email_key', 'User', ['email'], unique=True)
    op.create_index('User_externalUserId_idx', 'User', ['externalUserId'], unique=False)
    op.create_table('Verification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Verification_identifier_idx', 'Verification', ['identifier'], unique=False)
    op.create_table('Account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('accountId', sa.String(), nullable=False),
    sa.Column('providerId', sa.String(), nullable=False),
    sa.Column('accessToken', sa.String(), nullable=True),
    sa.Column('refreshToken', sa.String(), nullable=True),
    sa.Column('accessTokenExpiresAt', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('refreshTokenExpiresAt', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('idToken', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Account_providerId_accountId_key', 'Account', ['providerId', 'accountId'], unique=True)
    op.create_index('Account_userId_idx', 'Account', ['userId'], unique=False)
    op.create_table('AuditLog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=True),
    sa.Column('previousData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('newData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('AuditLog_createdAt_idx', 'AuditLog', ['createdAt'], unique=False)
    op.create_index('AuditLog_entity_entityId_idx', 'AuditLog', ['entity', 'entityId'], unique=False)
    op.create_index('AuditLog_userId_idx', 'AuditLog', ['userId'], unique=False)
    op.create_table('ImportJob',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('referenceYear', sa.Integer(), nullable=True),
    sa.Column('referenceMonth', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PARSING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'CANCELLED', name='ImportStatus'), nullable=False),
    sa.Column('totalFound', sa.Integer(), nullable=False),
    sa.Column('totalInserted', sa.Integer(), nullable=False),
    sa.Column('totalIgnored', sa.Integer(), nullable=False),
    sa.Column('totalUpdated', sa.Integer(), nullable=False),
    sa.Column('totalRejected', sa.Integer(), nullable=False),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('completedAt', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('errorMessage', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ImportJob_module_referenceYear_referenceMonth_idx', 'ImportJob', ['module', 'referenceYear', 'referenceMonth'], unique=False)
    op.create_index('ImportJob_status_idx', 'ImportJob', ['status'], unique=False)
    op.create_index('ImportJob_userId_idx', 'ImportJob', ['userId'], unique=False)
    op.create_table('IndicatorJustification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestedText', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('sourceImportId', sa.String(), nullable=True),
    sa.Column('sourceImportedAt', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.Column('createdById', sa.String(), nullable=False),
    sa.Column('updatedById', sa.String(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['createdById'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updatedById'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IndicatorJustification_createdById_idx', 'IndicatorJustification', ['createdById'], unique=False)
    op.create_index('IndicatorJustification_module_year_month_idx', 'IndicatorJustification', ['module', 'year', 'month'], unique=False)
    op.create_index('IndicatorJustification_module_year_month_key', 'IndicatorJustification', ['module', 'year', 'month'], unique=True)
    op.create_index('IndicatorJustification_updatedById_idx', 'IndicatorJustification', ['updatedById'], unique=False)
    op.create_table('IndicatorPublication',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('publishedById', sa.String(), nullable=False),
    sa.Column('publishedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('cycleYear', sa.Integer(), nullable=True),
    sa.Column('cycleSemester', sa.String(), nullable=True),
    sa.Column('periodStartYear', sa.Integer(), nullable=True),
    sa.Column('periodStartMonth', sa.Integer(), nullable=True),
    sa.Column('periodEndYear', sa.Integer(), nullable=True),
    sa.Column('periodEndMonth', sa.Integer(), nullable=True),
    sa.CheckConstraint('"cycleYear" IS NULL OR (("cycleSemester" = \'S2\' AND "periodStartYear" = "cycleYear" AND "periodStartMonth" = 6 AND "periodEndYear" = "cycleYear" AND "periodEndMonth" = 11) OR ("cycleSemester" = \'S1\' AND "periodStartYear" = "cycleYear" - 1 AND "periodStartMonth" = 12 AND "periodEndYear" = "cycleYear" AND "periodEndMonth" = 5))', name='IndicatorPublication_cycle_consistency_check'),
    sa.ForeignKeyConstraint(['publishedById'], ['User.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IndicatorPublication_active_cycle_key', 'IndicatorPublication', ['module', 'indicator', 'cycleYear', 'cycleSemester'], unique=True, postgresql_where=sa.text('"active" = true'))
    op.create_index('IndicatorPublication_module_indicator_active_publishedAt_idx', 'IndicatorPublication', ['module', 'indicator', 'active', 'publishedAt'], unique=False)
    op.create_index('IndicatorPublication_module_indicator_cycle_idx', 'IndicatorPublication', ['module', 'indicator', 'cycleYear', 'cycleSemester'], unique=False)
    op.create_index('IndicatorPublication_module_indicator_version_key', 'IndicatorPublication', ['module', 'indicator', 'version'], unique=True)
    op.create_index('IndicatorPublication_publishedById_idx', 'IndicatorPublication', ['publishedById'], unique=False)
    op.create_table('Session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('ipAddress', sa.String(), nullable=True),
    sa.Column('userAgent', sa.String(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Session_token_key', 'Session', ['token'], unique=True)
    op.create_index('Session_userId_idx', 'Session', ['userId'], unique=False)
    op.create_table('ImportBatch',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('importJobId', sa.String(), nullable=False),
    sa.Column('batchNumber', sa.Integer(), nullable=False),
    sa.Column('totalReceived', sa.Integer(), nullable=False),
    sa.Column('totalInserted', sa.Integer(), nullable=False),
    sa.Column('totalIgnored', sa.Integer(), nullable=False),
    sa.Column('totalUpdated', sa.Integer(), nullable=False),
    sa.Column('totalRejected', sa.Integer(), nullable=False),
    sa.Column('processedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['importJobId'], ['ImportJob.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ImportBatch_importJobId_batchNumber_key', 'ImportBatch', ['importJobId', 'batchNumber'], unique=True)
    op.create_table('ImportError',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('importJobId', sa.String(), nullable=False),
    sa.Column('batchNumber', sa.Integer(), nullable=True),
    sa.Column('rowNumber', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('rawData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['importJobId'], ['ImportJob.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ImportError_importJobId_idx', 'ImportError', ['importJobId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ImportError_importJobId_idx', table_name='ImportError')
    op.drop_table('ImportError')
    op.drop_index('ImportBatch_importJobId_batchNumber_key', table_name='ImportBatch')
    op.drop_table('ImportBatch')
    op.drop_index('Session_userId_idx', table_name='Session')
    op.drop_index('Session_token_key', table_name='Session')
    op.drop_table('Session')
    op.drop_index('IndicatorPublication_publishedById_idx', table_name='IndicatorPublication')
    op.drop_index('IndicatorPublication_module_indicator_version_key', table_name='IndicatorPublication')
    op.drop_index('IndicatorPublication_module_indicator_cycle_idx', table_name='IndicatorPublication')
    op.drop_index('IndicatorPublication_module_indicator_active_publishedAt_idx', table_name='IndicatorPublication')
    op.drop_index('IndicatorPublication_active_cycle_key', table_name='IndicatorPublication', postgresql_where=sa.text('"active" = true'))
    op.drop_table('IndicatorPublication')
    op.drop_index('IndicatorJustification_updatedById_idx', table_name='IndicatorJustification')
    op.drop_index('IndicatorJustification_module_year_month_key', table_name='IndicatorJustification')
    op.drop_index('IndicatorJustification_module_year_month_idx', table_name='IndicatorJustification')
    op.drop_index('IndicatorJustification_createdById_idx', table_name='IndicatorJustification')
    op.drop_table('IndicatorJustification')
    op.drop_index('ImportJob_userId_idx', table_name='ImportJob')
    op.drop_index('ImportJob_status_idx', table_name='ImportJob')
    op.drop_index('ImportJob_module_referenceYear_referenceMonth_idx', table_name='ImportJob')
    op.drop_table('ImportJob')
    op.drop_index('AuditLog_userId_idx', table_name='AuditLog')
    op.drop_index('AuditLog_entity_entityId_idx', table_name='AuditLog')
    op.drop_index('AuditLog_createdAt_idx', table_name='AuditLog')
    op.drop_table('AuditLog')
    op.drop_index('Account_userId_idx', table_name='Account')
    op.drop_index('Account_providerId_accountId_key', table_name='Account')
    op.drop_table('Account')
    op.drop_index('Verification_identifier_idx', table_name='Verification')
    op.drop_table('Verification')
    op.drop_index('User_externalUserId_idx', table_name='User')
    op.drop_index('User_email_key', table_name='User')
    op.drop_index('User_email_idx', table_name='User')
    op.drop_table('User')
    op.drop_index('ScorecardSnapshot_year_month_idx', table_name='ScorecardSnapshot')
    op.drop_index('ScorecardSnapshot_businessKey_key', table_name='ScorecardSnapshot')
    op.drop_table('ScorecardSnapshot')
    op.drop_index('RncRecord_year_month_idx', table_name='RncRecord')
    op.drop_index('RncRecord_unidade_idx', table_name='RncRecord')
    op.drop_index('RncRecord_businessKey_key', table_name='RncRecord')
    op.drop_table('RncRecord')
    op.drop_index('RdoRecord_year_month_idx', table_name='RdoRecord')
    op.drop_index('RdoRecord_statusDescricao_idx', table_name='RdoRecord')
    op.drop_index('RdoRecord_empresaNome_idx', table_name='RdoRecord')
    op.drop_index('RdoRecord_businessKey_key', table_name='RdoRecord')
    op.drop_table('RdoRecord')
    op.drop_index('IndicatorResult_module_year_month_idx', table_name='IndicatorResult')
    op.drop_index('IndicatorResult_module_indicator_unit_year_month_key', table_name='IndicatorResult')
    op.drop_table('IndicatorResult')
    op.drop_index('IdpRsoRecord_unit_rsoNumero_idx', table_name='IdpRsoRecord')
    op.drop_index('IdpRsoRecord_referenceYear_referenceMonth_idx', table_name='IdpRsoRecord')
    op.drop_index('IdpRsoRecord_businessKey_key', table_name='IdpRsoRecord')
    op.drop_table('IdpRsoRecord')
    op.drop_index('IdpRecord_year_month_idx', table_name='IdpRecord')
    op.drop_index('IdpRecord_unit_idx', table_name='IdpRecord')
    op.drop_index('IdpRecord_businessKey_key', table_name='IdpRecord')
    op.drop_table('IdpRecord')
    op.drop_index('FiveSRecord_year_month_idx', table_name='FiveSRecord')
    op.drop_index('FiveSRecord_unit_idx', table_name='FiveSRecord')
    op.drop_index('FiveSRecord_businessKey_key', table_name='FiveSRecord')
    op.drop_table('FiveSRecord')
    op.drop_table('AppSetting')
    op.drop_index('AccidentUnitRecord_year_month_unitKey_key', table_name='AccidentUnitRecord')
    op.drop_index('AccidentUnitRecord_year_month_idx', table_name='AccidentUnitRecord')
    op.drop_index('AccidentUnitRecord_unit_idx', table_name='AccidentUnitRecord')
    op.drop_table('AccidentUnitRecord')
    op.drop_index('AccidentMonthlyRecord_year_month_key', table_name='AccidentMonthlyRecord')
    op.drop_index('AccidentMonthlyRecord_year_month_idx', table_name='AccidentMonthlyRecord')
    op.drop_table('AccidentMonthlyRecord')
    # ### end Alembic commands ###
