<script setup lang="ts">
import { Plus, RefreshCw } from "lucide-vue-next";
import type { Role } from "~/types/api";
import { formatDate } from "~/utils/format";
interface UserRow {id:string;name:string;email:string;role:Role;active:boolean;authProvider:string;lastLoginAt:string|null;createdAt:string}
const api=useApi();const users=ref<UserRow[]>([]),loading=ref(true),busy=ref(false),message=ref("");const form=reactive<{name:string;email:string;role:Role}>({name:"",email:"",role:"VIEWER"});
async function load(){loading.value=true;try{users.value=(await api.get<{items:UserRow[]}>("/usuarios")).items;}catch(cause){message.value=cause instanceof Error?cause.message:"Erro ao carregar usuários.";}finally{loading.value=false;}}
async function create(){busy.value=true;try{await api.post("/usuarios",form);Object.assign(form,{name:"",email:"",role:"VIEWER"});message.value="Usuário criado.";await load();}catch(cause){message.value=cause instanceof Error?cause.message:"Erro ao criar usuário.";}finally{busy.value=false;}}
async function update(user:UserRow,body:Record<string,unknown>){busy.value=true;try{await api.patch(`/usuarios/${user.id}`,body);message.value="Usuário atualizado.";await load();}catch(cause){message.value=cause instanceof Error?cause.message:"Erro ao atualizar usuário.";}finally{busy.value=false;}}
onMounted(load);
</script>
<template><div class="stack"><section class="surface"><header class="surface-header"><div><h2>Novo usuário</h2><p>O vínculo OIDC poderá ser concluído no primeiro acesso corporativo.</p></div></header><form class="surface-body toolbar" @submit.prevent="create"><label class="field"><span>Nome</span><input v-model="form.name" required/></label><label class="field"><span>E-mail</span><input v-model="form.email" type="email" required/></label><label class="field"><span>Perfil</span><select v-model="form.role"><option>VIEWER</option><option>ANALYST</option><option>ADMIN</option></select></label><button class="btn primary" :disabled="busy"><Plus :size="15"/> Criar</button></form></section><section class="surface"><header class="surface-header"><div><h2>Usuários</h2><p>Perfis e status persistidos no backend são a fonte de verdade.</p></div><button class="btn btn-icon" @click="load"><RefreshCw :size="16"/></button></header><div class="surface-body stack"><p v-if="message" class="notice">{{message}}</p><div v-if="loading" class="loading-state"><div class="spinner"/></div><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Provedor</th><th>Último acesso</th><th>Status</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><input class="input" :value="user.name" @change="update(user,{name:($event.target as HTMLInputElement).value})"/></td><td>{{user.email}}</td><td><select class="input" :value="user.role" @change="update(user,{role:($event.target as HTMLSelectElement).value})"><option>VIEWER</option><option>ANALYST</option><option>ADMIN</option></select></td><td><span class="badge info">{{user.authProvider}}</span></td><td>{{formatDate(user.lastLoginAt,true)}}</td><td><button class="btn small" :class="user.active?'success':'danger'" @click="update(user,{active:!user.active})">{{user.active?'Ativo':'Inativo'}}</button></td></tr></tbody></table></div></div></section></div></template>
